[package]
name = "xc3_model_py"
version = "0.9.0"
authors = ["ScanMountGoat"]
edition = "2021"
readme = "../README.md"

[dependencies]
xc3_model = { git = "https://github.com/ScanMountGoat/xc3_lib", rev = "da996d1" }
xc3_lib = { git = "https://github.com/ScanMountGoat/xc3_lib", rev = "da996d1" }
xc3_model_py_derive = { path = "../xc3_model_py_derive" }
image_dds = "0.6.0"
pyo3 = { version = "0.22.3", features = ["extension-module", "indexmap", "py-clone"] }
numpy = { git = "https://github.com/PyO3/rust-numpy", rev = "505a79c" }
indexmap = "2.0.0"
glam = "0.28.0"
rayon = "1.7.0"
pyo3-log = "0.11.0"
anyhow = "1.0"
smol_str = "0.2.2"

[build-dependencies]
pyo3-build-config = "0.22.3"

[lib]
name = "xc3_model_py"
crate-type = ["cdylib"]
